# NumPy

- Open-source Python library
- Fundamental package for scientific computing   
- Multi-dimensional array
    - Matrix: dimension 2
    - Vector: dimension 1
    - Scalar: dimension 0
 

### Motivation example

In [1]:
# assume you are given the two matrices
m1 = [[12,7,3], 
      [4 ,5,6], 
      [7 ,8,9]] 

m2 = [[5,8,1], 
      [6,7,3], 
      [4,5,9]] 

# to compute m1 x m2, you need the following code

# we know m1 and m2 have the size (3,3), 
# so the result matrix also has the size (3,3)
# (3,3) x (3,3) => (3,3)
# we thus initialize the result matrix with all 0 values
res = [[0,0,0], 
       [0,0,0], 
       [0,0,0]]

# here we follow the matrix multiplication formula
for i in range(len(m1)): 
    for j in range(len(m2[0])): 

        # dot product
        for k in range(len(m2)):   
            # resulted matrix 
            res[i][j] += m1[i][k] * m2[k][j]

print(res)

[[114, 160, 60], [74, 97, 73], [119, 157, 112]]


In [2]:
# Import NumPy 
import numpy as np

m1 = np.array([[12,7,3], 
               [4 ,5,6], 
               [7 ,8,9]])
# print(m1)

m2 = np.array([[5,8,1], 
               [6,7,3], 
               [4,5,9]]) 

res = m1.dot(m2)
print(res)

[[114 160  60]
 [ 74  97  73]
 [119 157 112]]


### Multi-dimensional arrays: `ndarray`


### Create ndarray from existing data

In [3]:
# We can create arrays from existing data by calling the function np.array
print("Create nd arrays with different dimensions\n")

# initialize an array (1D array)
print("Create a vector / 1D-array")
arr1 = np.array([1,2,3,4,5,6])
print("arr1:", arr1) # print the array
print() # print an empty line

# 0D array
print("initialize a scalar / 0D-array")
arr0 = np.array(2)
print("arr0:", arr0)
print() # print an empty line

# 2D array
print("initialize a matrix / 2D-array")
arr2 = np.array([[1,2,3], [4,5,6]]) 
print("arr2:")
print(arr2)
print() # print an empty line


print("------------\n")


print("Check the dimensions of the arrays:")
print("arr0.ndim:", arr0.ndim) # check the dimension of the array
print("arr1.ndim:", arr1.ndim)
print("arr2.ndim:", arr2.ndim)

print()
print("Check the shape of the arrays:")
print("arr1.shape:", arr1.shape)
print("arr2.shape:", arr2.shape) # the shape of the matrix

print("\n------------\n")

a = np.array([1,2,3,4,5,6])
b = np.array([[1,2,3,4,5,6]])
c = np.array([[1], [2], [3], [4], [5], [6]])
print("Consider the following three arrays:")
print("a =", a)
print("b =", b)
print("c =")
print(c)
print()

print("a.ndim:", a.ndim)
print("a.shape:", a.shape)

print("b.ndim:", b.ndim, ", c.ndim:", c.ndim)
print("b.shape:", b.shape, ", c.shape", c.shape)


Create nd arrays with different dimensions

Create a vector / 1D-array
arr1: [1 2 3 4 5 6]

initialize a scalar / 0D-array
arr0: 2

initialize a matrix / 2D-array
arr2:
[[1 2 3]
 [4 5 6]]

------------

Check the dimensions of the arrays:
arr0.ndim: 0
arr1.ndim: 1
arr2.ndim: 2

Check the shape of the arrays:
arr1.shape: (6,)
arr2.shape: (2, 3)

------------

Consider the following three arrays:
a = [1 2 3 4 5 6]
b = [[1 2 3 4 5 6]]
c =
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]

a.ndim: 1
a.shape: (6,)
b.ndim: 2 , c.ndim: 2
b.shape: (1, 6) , c.shape (6, 1)


### Built-in functions for creating ndarrays 

In [4]:
# functions for creating arrays

# create arrays of all zero
zeros = np.zeros((2,3)) # create a 2x3 matrix of all 0
print("Create a 2x3 matrix of 0: ")
print(zeros)
print()

# create arrays of all one
ones = np.ones((6,1)) # create a 6,1 matrix of all 1
print("Create a 6x1 matrix of 1: ")
print(ones)
print()

# create identity matrices 
# An identity matrix is a square matrix that has 1's along the main diagonal 
# and 0's for all other entries.
eye = np.eye(5) # identity matrix with shape 5x5
print("Create a 5x5 identity matrix:")
print(eye)
print("Shape of the identity matrix:", eye.shape)
print()


# create arrays with random values in [0,1)
print("Create a 3x2 matrix with random values in [0,1):")
r = np.random.random((3,2)) # create an array with random values from 0 to 1
print(r)
print()

# numpy.random.randint
# numpy.random.randn

# https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html
# https://numpy.org/doc/stable/reference/random/generated/numpy.random.randn.html


Create a 2x3 matrix of 0: 
[[0. 0. 0.]
 [0. 0. 0.]]

Create a 6x1 matrix of 1: 
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]

Create a 5x5 identity matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Shape of the identity matrix: (5, 5)

Create a 3x2 matrix with random values in [0,1):
[[0.69552046 0.58711435]
 [0.37731921 0.20676143]
 [0.63303011 0.79195422]]



### Create ndarrays from csv files

In [5]:
X = np.loadtxt(open("./california_housing_train.csv", "rb"), delimiter=",", skiprows=1)     #skiprows skip the first n lines
 
X.shape

(17000, 9)

### Access the elements of ndarrays using indexing and slicing

In [8]:
# indexing 

# create a 3x4 matrix
m = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print("Create the matrix :")
print(m)
print()

# access an element by indeces
print("Access the element at the second row and first column:")
# Python follows zero-based numbering, 
# i.e., the first element is assigned index 0 rather 1
print("m[1,0]:", m[1,0]) # The first number refers to the index of the row 
                           # while the second number refers to that of the column")
print()
print("------------\n")

# slicing

# access multiple elements
print("Use slicing to select a range of elements\n")

# [0:5] => [0,1,2,3,4]
# [1:5] => [1,2,3,4]
# [:5] => [0,1,2,3,4]


print("Extract elements that are in the first two rows and the 2nd and 3rd columns:")
print("m[:2,1:3]:") 
print(m[:2,1:3])
print("the slicing 1:3 means [1,2], i.e., second and third. Note 3 is excluded.")
print("the slicing :2 is equivalent to 0:2, which means indeces [0,1]")
print()
print("The extracted sub-matrix has the shape 2x2:")
print("m[:2,1:3].shape:", m[:2,1:3].shape)


print("\n----------\n")

print("Extract the second row of the matrix:")
print(": means taking all elements of the dimension")
print("m[1,:]:", m[1,:]) # : means taking all elements of the dimension
print("m[1,:].shape:", m[1,:].shape)

print()

print("Extract the first column of the matrix a")
print("m[:,0]:", m[:,0]) # 
print("m[:,0].shape:", m[:,0].shape)

print()

print("Note mixing integer indexing with slices yields a vector rather than a matrix.")
print("m[:,0].shape:", m[:,0].shape)
print("Use only slices yields a matrix:")
print("m[:,0:1].shape:", m[:,0:1].shape)
print(m[:,0:1])


Create the matrix :
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Access the element at the second row and first column:
m[1,0]: 4

------------

Use slicing to select a range of elements

Extract elements that are in the first two rows and the 2nd and 3rd columns:
m[:2,1:3]:
[[2 3]
 [5 6]]
the slicing 1:3 means [1,2], i.e., second and third. Note 3 is excluded.
the slicing :2 is equivalent to 0:2, which means indeces [0,1]

The extracted sub-matrix has the shape 2x2:
m[:2,1:3].shape: (2, 2)

----------

Extract the second row of the matrix:
: means taking all elements of the dimension
m[1,:]: [4 5 6]
m[1,:].shape: (3,)

Extract the first column of the matrix a
m[:,0]: [ 1  4  7 10]
m[:,0].shape: (4,)

Note mixing integer indexing with slices yields a vector rather than a matrix.
m[:,0].shape: (4,)
Use only slices yields a matrix:
m[:,0:1].shape: (4, 1)
[[ 1]
 [ 4]
 [ 7]
 [10]]


#### **Exercise**: Split a dataset into training data and test data

In [6]:
# load the sample dataset to the variable X
data = np.loadtxt(open("./california_housing_train.csv", "rb"), delimiter=",", skiprows=1) 

print("data.shape:", data.shape)
print("The matrix X has {} rows and {} columns, i.e., {} records and {} attributes".format(data.shape[0], data.shape[1], data.shape[0], data.shape[1]))

print("\n-----------------\n")

# Task 1: split the matrix to the feature matrix X and the label vector y
# The last column of the matrix is the label vector 
X = data[:, :-1]
y = data[:, -1]
print("feature matrix X:", X.shape)
print("label vector y:", y.shape)

# Task 2:
# We want to use the first 80% rows as training data, and the remaining 20% as test data
# get X_train, y_train, X_test, y_test

# compute the number of rows in the training data
train_size = int(X.shape[0] * 0.8) # cast the number to an integer
print("Training data size:", train_size)

X_train = X[:train_size, :] # the first 'train_size' rows of X
X_test = X[train_size:, :] # rows after the train_size th row
y_train = y[:train_size]
y_test = y[train_size:]

print("X_train.shape:", X_train.shape)
print("X_test.shape:", X_test.shape)
print("y_train.shape:", y_train.shape)
print("y_test.shape:", y_test.shape)


data.shape: (17000, 9)
The matrix X has 17000 rows and 9 columns, i.e., 17000 records and 9 attributes

-----------------

feature matrix X: (17000, 8)
label vector y: (17000,)
Training data size: 13600
X_train.shape: (13600, 8)
X_test.shape: (3400, 8)
y_train.shape: (13600,)
y_test.shape: (3400,)


### Boolean Masks of arrays


In [7]:
# Given the vector v:
v = np.array([10,7,3,4,2,6,9,8,9,1])

print("Given the vector v: ")
print(v)
print()

# Check for each element of the array whether the condition is satisfied. 
print("Select the elements that are equal to 9:")
# An array of boolean values indicating whether the condition is satisfied. 
boolean_mask = v == 9
print(boolean_mask)
print()

print("Select the elements that are larger than 5:")
boolean_mask = v > 5
print(boolean_mask)
print()

print("Values that are larger than 5:")
print(v[v > 5])
print()
print("----------------")
print()

# Boolean masks on higher dimensions  
m = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print("Given the matrix m:")
print(m)
print()

print("Select the elements that are larger than 5:")
boolean_mask = m > 5
print(boolean_mask)
print()

print("Select the rows such that the first column of the rows is larger than 5:")
print(m[:, 0])
boolean_mask = m[:, 0] > 5
print(boolean_mask)
print()
print(m[boolean_mask, :])

Given the vector v: 
[10  7  3  4  2  6  9  8  9  1]

Select the elements that are equal to 9:
[False False False False False False  True False  True False]

Select the elements that are larger than 5:
[ True  True False False False  True  True  True  True False]

Values that are larger than 5:
[10  7  6  9  8  9]

----------------

Given the matrix m:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Select the elements that are larger than 5:
[[False False False]
 [False False  True]
 [ True  True  True]
 [ True  True  True]]

Select the rows such that the first column of the rows is larger than 5:
[ 1  4  7 10]
[False False  True  True]

[[ 7  8  9]
 [10 11 12]]


#### **Exercise**: Select the rows that have "median_house_value" > 100,000

In [8]:
# consider the california housing data
print("X.shape:", X.shape)
print("y.shape:", y.shape)

# Task: Select the data records in X that have y-values larger than 100000
mask = y > 100000 
# print(mask)
m = X[mask, :] # select the rows from X
m.shape


X.shape: (17000, 8)
y.shape: (17000,)


(13983, 8)

### Reshape ndarrays

In [9]:
# reshape the arrays

vec = np.array([1,2,3,4,5,6]) # init a vector
print("Create the vector vec =", vec)
print("vec.shape:", vec.shape)

print("\n-----------\n")

print("Convert a vector with six elements to a 2x3 matrix")

matrix = vec.reshape((2,3))
print("matrix:")
print(matrix)
print("matrix.shape:", matrix.shape)
print()

print("Flatten the matrix to a vector")
vec2 = matrix.reshape(-1) # -1 means reshaping the array into a 1D array
print("vec2:")
print(vec2)
print("vec2.shape:", vec2.shape)


Create the vector vec = [1 2 3 4 5 6]
vec.shape: (6,)

-----------

Convert a vector with six elements to a 2x3 matrix
matrix:
[[1 2 3]
 [4 5 6]]
matrix.shape: (2, 3)

Flatten the matrix to a vector
vec2:
[1 2 3 4 5 6]
vec2.shape: (6,)


### Iterate ndarrays

In [10]:
# create a 3x4 matrix
m = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
m = m.reshape((3,4)) # reshape the vector to a 3x4 matrix

print("create a 3x4 matrix m = ")
print(m)
print("m.shape:", m.shape)

print("\n-----------\n")
print("Iterate by rows using 'for row in m:'")
# for each row
for row in m:
  print(row)

print("\n-----------\n")
print("Iterate by columns using 'for row in m.T:'")

# we can iterate the rows of the transpose of the matrix
print()
print("m.T:")
print(m.T)
print()

# for each col
for col in m.T: # m.T means the transpose of m
  print(col)

print("where m.T means the transpose of m.")
print("note the transpose operation is not costly as it just changes the 'strides' of numpy arrays")

# note transpose operation is not costly as it just changes the 'strides' of array

print("\n-----------\n")
print("Iterate by elements using nested for loops:")
# for each element
for row in m:
  for elem in row:
    print(elem)

print("\n-----------\n")

print("Enumerate elements with indices:")
print("for i, elem in np.ndenumerate(m):")
# enumerate elements with index
for i, elem in np.ndenumerate(m):
  print(i, elem)




create a 3x4 matrix m = 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
m.shape: (3, 4)

-----------

Iterate by rows using 'for row in m:'
[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]

-----------

Iterate by columns using 'for row in m.T:'

m.T:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]

[1 5 9]
[ 2  6 10]
[ 3  7 11]
[ 4  8 12]
where m.T means the transpose of m.
note the transpose operation is not costly as it just changes the 'strides' of numpy arrays

-----------

Iterate by elements using nested for loops:
1
2
3
4
5
6
7
8
9
10
11
12

-----------

Enumerate elements with indices:
for i, elem in np.ndenumerate(m):
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
(2, 0) 9
(2, 1) 10
(2, 2) 11
(2, 3) 12


### Concatenation of ndarrays

In [11]:
# consider the two vectors
print("Consider the two vectors")
m1 = np.array([[1,2,3], [4,5,6]])
m2 = np.array([[7,8,9], [10,11,12]])
print("m1:")
print(m1)
print("m2:")
print(m2)

print("\n---------------\n")

print("stack along rows / concatenate matrices horizontally")
print(np.hstack((m1, m2)))
print()

print("stack along columns / concatenate matrices vertically")
print(np.vstack((m1, m2)))
print()


Consider the two vectors
m1:
[[1 2 3]
 [4 5 6]]
m2:
[[ 7  8  9]
 [10 11 12]]

---------------

stack along rows / concatenate matrices horizontally
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]

stack along columns / concatenate matrices vertically
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]



#### **Exercise**: Add the bias column to the front of the matrix

In [12]:
# init the given matrix
print("Consider the given matrix m:")
m = np.array([1,2,3,4,5,6,7,8,9,10,11,12]).reshape(3,4)
print(m)
print("m.shape:", m.shape)

print("\n---------------\n")

# Task: add the bias feature to the front of the matrix m
print("Create the bias column")
vec = np.ones((m.shape[0], 1)) # m.shape[0] = the number of rows in m
print(vec)

print("Concatenate the column and the matrix")
m = np.hstack((vec, m))
print(m)


Consider the given matrix m:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
m.shape: (3, 4)

---------------

Create the bias column
[[1.]
 [1.]
 [1.]]
Concatenate the column and the matrix
[[ 1.  1.  2.  3.  4.]
 [ 1.  5.  6.  7.  8.]
 [ 1.  9. 10. 11. 12.]]


### Arithmetic operators



NumPy provdes some basic operators.

In [13]:
print("Consider the two 2x3 matrices:")
m1 = np.array([1,2,3,4,5,6]).reshape((2,3))
m2 = np.array([4,5,6,7,8,9]).reshape((2,3))
print("m1:")
print(m1)
print("m2:")
print(m2)

print("\n--------------\n")

print("Square root:")
print("np.sqrt(m1):")
print(np.sqrt(m1))

print("\n--------------------\n")

print("Sum of all values of m1")
print("np.sum(m1):", np.sum(m1)) # sum of all values
print()
print("Sum the rows")
print("np.sum(m1, axis=0):", np.sum(m1, axis=0)) # sum along rows
print()
print("Sum the columns")
print("np.sum(m1, axis=1):", np.sum(m1, axis=1)) # sum along cols


print("\n--------------\n")

print("Average:")
print("np.mean(m1) =", np.mean(m1))
print()
print("Average of the rows:")
print("np.mean(m1, axis=0) =", np.mean(m1, axis=0))
print()
print("Average of the columns:")
print("np.mean(m1, axis=1) =", np.mean(m1, axis=1))

print("\n--------------\n")

print("Max / Min:")
print("np.max(m1) =", np.max(m1))
print("np.min(m1) =", np.min(m1))


print("\n--------------\n")

print("m1 + m2:")
print(m1 + m2)
print()

print("m1 - m2:")
print(m1 - m2)
print()

print("m1 * m2:")
print(m1 * m2)


Consider the two 2x3 matrices:
m1:
[[1 2 3]
 [4 5 6]]
m2:
[[4 5 6]
 [7 8 9]]

--------------

Square root:
np.sqrt(m1):
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]

--------------------

Sum of all values of m1
np.sum(m1): 21

Sum the rows
np.sum(m1, axis=0): [5 7 9]

Sum the columns
np.sum(m1, axis=1): [ 6 15]

--------------

Average:
np.mean(m1) = 3.5

Average of the rows:
np.mean(m1, axis=0) = [2.5 3.5 4.5]

Average of the columns:
np.mean(m1, axis=1) = [2. 5.]

--------------

Max / Min:
np.max(m1) = 6
np.min(m1) = 1

--------------

m1 + m2:
[[ 5  7  9]
 [11 13 15]]

m1 - m2:
[[-3 -3 -3]
 [-3 -3 -3]]

m1 * m2:
[[ 4 10 18]
 [28 40 54]]


### Matrix operators

In [14]:
# the product of matrices / vectors

print("Consider the two vectors:")
# vectors
v = np.array([1,2,3,4,5,6])
w = np.array([6,7,8,9,10,11])
print("v:", v)
print("w:", w)
print()



# 1*6 + ...
print("Dot product")
print("v.dot(w):", v.dot(w)) # inner product of v and w
print("np.dot(v, w):", np.dot(v, w)) # same as above


print("\n--------------------\n")
print("Consider the two matrices:")
m1 = v.reshape((2,3))
m2 = w.reshape((3,2))
print("m1:")
print(m1)
print("m2:")
print(m2)
print()


print("Matrix multiplication")

# (2,3) x (3,2) => (2,2)
print("m1.shape:", m1.shape)
print("m2.shape:", m2.shape)
print("(2,3) x (3,2) => (2,2)")
print()

print("m1.dot(m2):")
print(m1.dot(m2))

print("m1.dot(m2).shape:", m1.dot(m2).shape)


print("\n--------------------\n")
print("Transpose of m1")
# transpose
print("m1.T")
print(m1.T)
print("m1.T.shape:", m1.T.shape)

print("\n--------------------\n")
print("Inverse of the matrix")
print(np.array([[1,2], [3,4]]))
print()
# Inverse
# np.linalg.inv(np.eye(5))
np.linalg.inv(np.array([[1,2], [3,4]]))

Consider the two vectors:
v: [1 2 3 4 5 6]
w: [ 6  7  8  9 10 11]

Dot product
v.dot(w): 196
np.dot(v, w): 196

--------------------

Consider the two matrices:
m1:
[[1 2 3]
 [4 5 6]]
m2:
[[ 6  7]
 [ 8  9]
 [10 11]]

Matrix multiplication
m1.shape: (2, 3)
m2.shape: (3, 2)
(2,3) x (3,2) => (2,2)

m1.dot(m2):
[[ 52  58]
 [124 139]]
m1.dot(m2).shape: (2, 2)

--------------------

Transpose of m1
m1.T
[[1 4]
 [2 5]
 [3 6]]
m1.T.shape: (3, 2)

--------------------

Inverse of the matrix
[[1 2]
 [3 4]]



array([[-2. ,  1. ],
       [ 1.5, -0.5]])

#### **Exercise**: Given a matrix $X$, compute the hat matrix $$X (X^T X)^{-1}X^T$$

In [15]:
# init the matrix 
print("Consider the matrix m:")
m = np.array([1,2,3,4,5,6]).reshape(3,2)
print(m)
print("m.shape:", m.shape)
print()

m1 = m.T.dot(m) # X^T X
m2 = np.linalg.inv(m1) # (X^T X)^-1
m3 = m.dot(m2).dot(m.T) # X(X^T X)^-1X^T
print(m3)

Consider the matrix m:
[[1 2]
 [3 4]
 [5 6]]
m.shape: (3, 2)

[[ 0.83333333  0.33333333 -0.16666667]
 [ 0.33333333  0.33333333  0.33333333]
 [-0.16666667  0.33333333  0.83333333]]


### Broadcasting

Broadcast enables the arithmetic operations on ndarrays with different dimensions. 

In [19]:
print("Consider the given matrix m:")
m = np.array([[2,3,4,5], [3,4,5,6], [4,5,6,7]])
print(m)
print("m.shape:", m.shape)

print("\n-----------------\n")

print("Add 1 to every element of m")
print("m + 1:") # add 1 to each element of m
print(m + 1)
print()

print("Power of 2")
print("m ** 2:") # in Python, x**2 = x^2
print(m ** 2) 


Consider the given matrix m:
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]
m.shape: (3, 4)

-----------------

Add 1 to every element of m
m + 1:
[[3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]

Power of 2
m ** 2:
[[ 4  9 16 25]
 [ 9 16 25 36]
 [16 25 36 49]]


We can add a vector to each row/column of a matrix (if their sizes are valid). 

In [16]:
# suppose we want to add the vector to each row of the matrix m
v = np.array([1,2,3,4])
m = np.array([[2,3,4,5], [3,4,5,6], [4,5,6,7]])
print("Consider the vector v and the matrix m")
print("v:", v)
print("v.shape:", v.shape)
print()
print("m:")
print(m)
print("m.shape", m.shape)

print("\n-----------------\n")
# by broadcasting
print("Add v to each row of m by broadcasting:")
m += v
print("m += v")
print("m:")
print(m)


Consider the vector v and the matrix m
v: [1 2 3 4]
v.shape: (4,)

m:
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]
m.shape (3, 4)

-----------------

Add v to each row of m by broadcasting:
m += v
m:
[[ 3  5  7  9]
 [ 4  6  8 10]
 [ 5  7  9 11]]


#### **Exercise**: Add a vector to each column of a matrix

In [21]:
# init the vector and the matrix
v = np.array([1,2,3])
m = np.array([[2,3,4,5], [3,4,5,6], [4,5,6,7]])
print("Consider the vector v and the matrix m")
print("v:", v)
print("v.shape:", v.shape)
print()
print("m:")
print(m)
print("m.shape", m.shape)

print("\n-------------\n")

# Hint: 
#   1. transpose the matrix 
#   2. add the vector to each row of the transpose matrix
#   3. transpose the matrix back

# option 1
m1 = (m.T + v).T

# option 2
m2 = m + v.reshape((3,1))


Consider the vector v and the matrix m
v: [1 2 3]
v.shape: (3,)

m:
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]
m.shape (3, 4)

-------------



#### **Exercise**: Min-Max Normalization

For each column of the matrix, scale data to be in the range from 0 to 1. 

min-max normalisation: m_norm = (m - min) / (max - min)

In [20]:
# init the matrix
m = np.random.random((5,4)) * 100
print("Consider the matrix m with random values from 0 to 100")
print(m)
print("m.shape", m.shape)

# The task is to normalise the data in each column using the min-max normalisation:
# m_norm = (m - min) / max - min),
# where min and max are the minimal and maximum values in the column

print("\n-------------\n")

m_min = np.min(m, axis=0)   # np.min returns the minumum of each column of the matrix m
m_max = np.max(m, axis=0)   # np.max returns the maximum of each column of the matrix m
m_norm = (m - m_min) / (m_max - m_min)

print("Normalized m: ")
print(m_norm)


Consider the matrix m with random values from 0 to 100
[[26.63985764  3.49520598 29.05165929 79.77412793]
 [40.04049257 33.26338226 22.54570981 93.24914137]
 [20.50475033 20.38161879 79.58564018  0.81384579]
 [60.54713062 79.47333032 28.07603991 77.43284562]
 [57.86248672 43.25130793 77.49705512 55.41869516]]
m.shape (5, 4)

-------------

Normalized m: 
[[0.15321535 0.         0.11405956 0.85422221]
 [0.48787665 0.3917993  0.         1.        ]
 [0.         0.22225362 1.         0.        ]
 [1.         1.         0.09695541 0.82889333]
 [0.93295494 0.52325722 0.96338381 0.59073592]]
